### ISSUE TITLE
Add Roles in Users

### ISSUE THREAD

**Issue by jljunior3** [laravel-doctrine/acl#17]
Hi, 
How do I add role in User?

**Comment by FoxxMD** [comment]
Please read through the [documentation](http://www.laraveldoctrine.org/docs/1.0/acl/roles)!

You will need to
1. Define a `Role` entity in your doctrine mappings that implements `LaravelDoctrine\ACL\Contracts\Role`
2. Define the relationship between your `User` entity and a `Role` entity -- This can be done using `LaravelDoctrine\ACL\Mappings\HasRoles` or manually in your mappings/annotations

At this point `User` and `Role` are normal doctrine entities and you can (read: need to) implement whatever method you would like in order to add roles to a user. eg 

``` php
$user->addRole($someRole); 
$em->persist($user);
$em->flush();
```

Additionally, you can add some built in functionality for reading roles by implementing `LaravelDoctrine\ACL\Contracts\HasRoles` on your `User` using the trait `LaravelDoctrine\ACL\Roles`

Please let me know if that answers your question!

**Comment by jljunior3** [comment]
@FoxxMD thank you so much !
